config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  # resources :merchants do
  #   resources :items, only: [:index, :new, :create]
  # end

  get '/merchants', to: 'merchants#index'
  post '/merchants', to: 'merchants#create'
  get '/merchants/new', to: 'merchants#new'

  get '/merchants/:id', to: 'merchants#show'
  get '/merchants/:id/edit', to: 'merchants#edit'
  patch '/merchants/:id', to: 'merchants#update'
  delete '/merchants/:id', to: 'merchants#destroy'

  get '/merchants/:merchant_id/items', to: 'items#index'
  post '/merchants/:merchant_id/items', to: 'items#create'
  get '/merchants/:merchant_id/items/new', to: 'items#new'


  # resources :items, except: [:new, :create] do
  #   resources :reviews, only: [:new, :create]
  # end

  get '/items', to: 'items#index'
  get '/items/:id/edit', to: 'items#edit'
  get '/items/:id', to: 'items#show'
  patch '/items/:id', to: 'items#update'
  delete '/items/:id', to: 'items#destroy'

  post '/items/:item_id/reviews', to: 'reviews#create'
  get '/items/:item_id/reviews/new', to: 'reviews#new'

  # resources :reviews, only: [:edit, :update, :destroy]

  get '/reviews/:id/edit', to: 'reviews#edit'
  patch '/reviews/:id', to: 'reviews#update'
  delete '/reviews/:id', to: 'reviews#destroy'

  post '/cart/:item_id', to: 'cart#add_item'
  get '/cart', to: 'cart#show'
  delete '/cart', to: 'cart#empty'
  delete '/cart/:item_id', to: 'cart#remove_item'
  patch '/cart/:item_id/:increment_decrement', to: 'cart#increment_decrement'

  get '/profile/orders', to: 'user_orders#index'
  get '/profile/orders/:id', to: 'user_orders#show'
  get '/profile/orders/:address_id/new', to: 'user_orders#new'
  post '/profile/orders/:address_id', to: 'user_orders#create'
  get '/profile/orders/:id/edit', to: 'user_orders#edit'
  patch '/profile/orders/:id/addresses/:address_id', to: 'user_orders#update'
  patch '/profile/orders/:id', to: 'user_orders#cancel'


  get '/profile', to: 'users#show'
  get '/register', to: 'users#new'
  post '/users', to: 'users#create'
  get '/profile/edit', to: 'users#edit'
  patch '/profile', to: 'users#update'


  get '/profile/addresses', to: 'addresses#index'
  get '/profile/addresses/:id/edit', to: 'addresses#edit'
  patch '/profile/addresses/:id', to: 'addresses#update'
  get '/profile/addresses/new', to: 'addresses#new'
  post '/profile/addresses', to: 'addresses#create'
  delete '/profile/addresses/:id', to: 'addresses#destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  namespace :merchant do
    # resources :items, except: [:show]

    get '/items', to: 'items#index'
    post '/items', to: 'items#create'
    get '/items/new', to: 'items#new'
    get '/items/:id/edit', to: 'items#edit'
    patch '/items/:id', to: 'items#update'
    delete '/items/:id', to: 'items#destroy'


    root 'dashboard#index'

    get '/orders/:id', to: 'orders#show'
    patch '/orders/:order_id/item_orders/:item_order_id', to: 'orders#update'
  end

  namespace :admin do
    # resources :users, only: [:index, :show]

    get '/users', to: 'users#index'
    get '/users/:id', to: 'users#show'

    root 'dashboard#index'

    get '/users/:id/orders', to: 'user_orders#index'
    get '/users/:user_id/orders/:order_id', to: 'user_orders#show'
    patch '/users/:user_id/orders/:order_id', to: 'user_orders#update'

    get '/merchants/:id', to: 'dashboard#merchant_index'
    patch '/merchants/:id', to: 'merchants#update'
    get '/merchants/:merchant_id/orders/:order_id', to: 'merchant_orders#show'
    patch '/merchants/:merchant_id/orders/:order_id/item_orders/:item_order_id', to: 'merchant_orders#update'
  end
end

app/views/partials/_address_form.html.erb
<%= form_tag path, method: method do %>
  <section class='form-group form-width'>
    <p>
      <%= label_tag :nickname %>
      <%= text_field_tag :nickname, nickname, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :address %>
      <%= text_field_tag :address, address, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :city %>
      <%= text_field_tag :city, city, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :state %>
      <%= text_field_tag :state, state, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :zip %>
      <%= text_field_tag :zip, zip, class: 'form-control' %>
    </p>

    <p class='justify-content-center row'>
      <%= submit_tag button_text, class: 'btn btn-primary mt-2' %>
    </p>
  </section>
<% end %>

app/views/partials/_item_form.html.erb
<%= form_tag path, method: method do %>
  <section class='form-group form-width'>
    <p>
      <%= label_tag :name %>
      <%= text_field_tag :name, name, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :description %>
      <%= text_area_tag :description, description, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :price %>
      <%= number_field_tag :price, price, class: 'form-control', step: 0.01 %>
    </p>

    <p>
      <%= label_tag :image %>
      <%= text_field_tag :image, image, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :inventory %>
      <%= number_field_tag :inventory, inventory, class: 'form-control' %>
    </p>

    <p class='justify-content-center row'>
      <%= submit_tag button_text, class: 'btn btn-primary mt-2' %>
    </p>
  </section>
<% end %>

app/views/partials/_merchant_dashboard.html.erb
<h1 class="mt-4 mb-3">Merchant Dashboard</h1>

<section id='merchant-info'>
  <h3 class="mt-4 mb-3 text-center"><%= link_to @merchant.name, "/merchants/#{@merchant.id}" %></h3>
  <h6 class="address text-center">
    <%= @merchant.address %><br>
    <%= @merchant.city %>, <%= @merchant.state %> <%= @merchant.zip %>
  </h6>
  <p align="center"><%= link_to "My Items", merchant_items_path, class: 'btn btn-primary mt-3' %></p>
</section>

<hr class="mt-4 mb-3">

<% if @merchant.pending_orders.any? %>
  <h2 class="mt-4 mb-4 text-center">Pending Orders</h2>

  <table class="table table-striped table-bordered cart-table">
    <thead>
      <tr>
        <th scope="col">Order ID</th>
        <th scope="col">Date Created</th>
        <th scope="col">Quantity of Your Items</th>
        <th scope="col">Total Value of Your Items</th>
      </tr>
    </thead>
    <tbody>
      <% @merchant.pending_orders.each do |order| %>
        <tr id="order-<%= order.id %>">
          <th scope="row"><%= link_to "#{order.id}", merchant_orders_path + "#{order.id}" %></th>
          <td><%= order.created_at.strftime("%m/%d/%Y") %></td>
          <td class='total-quantity'><%= @merchant.total_items_in_order(order) %></td>
          <td><%= number_to_currency(@merchant.total_value_in_order(order)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2 class="mt-4 mb-4 text-center">No Pending Orders</h2>
<% end %>

app/views/partials/_merchant_form.html.erb
<%= form_tag path, method: method do %>
  <section class='form-group form-width'>
    <p>
      <%= label_tag :name %>
      <%= text_field_tag :name, name, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :address %>
      <%= text_field_tag :address, address, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :city %>
      <%= text_field_tag :city, city, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :state %>
      <%= text_field_tag :state, state, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :zip %>
      <%= text_field_tag :zip, zip, class: 'form-control' %>
    </p>

    <p class='justify-content-center row'>
      <%= submit_tag button_text, class: 'btn btn-primary mt-2' %>
    </p>
  </section>
<% end %>

app/views/partials/_merchant_order_show.html.erb
<h1 class="mt-4 mb-4">Order #<%= @order.id %></h1>

<hr class="mt-4 mb-3">

<section id="customer-info">
  <h2 class="text-center mb-4 mt-4">Customer Information</h2>
  <h5 class="text-center"><%= @order.user.name %></h5>
  <h6 class="text-center">
    <%= @order.address.address %><br>
    <%= @order.address.city %>, <%= @order.address.state %> <%= @order.address.zip %>
  </h6>
</section>

<hr class="mt-5">

<h2 class="text-center mb-4 mt-4">Item Details</h2>

<table class="table table-striped table-bordered cart-table">
  <thead>
    <tr>
      <th scope="col">Item</th>
      <th scope="col">Image</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @merchant.item_orders_in_order(@order).each do |item_order|%>
      <tr>
        <section id = "item-<%= item_order.item_id %>">
          <th><%= link_to item_order.item.name, "/items/#{item_order.item_id}" %></th>
          <td align='center'><%= image_tag item_order.item.image %></td>
          <td><%= number_to_currency(item_order.price)%></td>
          <td><%= item_order.quantity %></td>
          <td align="center">
            <% if item_order.unfulfilled? %>
              <p class="inactive">Unfulfilled</p>
              <% if item_order.enough_inventory? %>
                <%= button_to 'Fulfill Item', fulfill_item_path + "#{item_order.id}", method: :patch, class: 'btn btn-outline-success' %>
              <% else %>
                <p>Cannot Fulfill <br>(Not Enough Inventory)</p>
              <% end %>
            <% elsif item_order.fulfilled? %>
              <p class="active">Fulfilled</p>
            <% elsif item_order.cancelled? %>
              <p class="inactive">Cancelled</p>
            <% end %>
          </td>
        </section>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/partials/_review_form.html.erb
<%= form_tag path, method: method do %>
  <section class='form-group form-width'>
    <p>
      <%= label_tag :title %>
      <%= text_field_tag :title, title, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag 'Review Content' %>
      <%= text_area_tag :content, content, class: 'form-control' %>
    </p>

    <p>
      <%= label_tag :rating %>
      <%= number_field_tag :rating, rating, class: 'form-control' %>
    </p>

    <p class='justify-content-center row'>
      <%= submit_tag button_text, class: 'btn btn-primary mt-2' %>
    </p>
  </section>
<% end %>

app/views/partials/_user_order_show.html.erb
<h1 class="mt-4 mb-4">Order #<%= @order.id %></h1>
<center>
  <h6>Address</h6>
  <table class="address-info">
    <tr>
      <td><%= @order.address.nickname %></td>
      <td><%= @order.address.address %></td>
      <td><%= @order.address.city %></td>
      <td><%= @order.address.state %></td>
      <td><%= @order.address.zip %></td>
    </tr>
  </table>
</center>
<table class="table table-striped table-bordered cart-table">
  <thead>
    <tr>
      <th scope="col">Order ID</th>
      <th scope="col">Date Created</th>
      <th scope="col">Date Updated</th>
      <th scope="col">Current Status</th>
      <th scope="col">Number of Items</th>
      <th scope="col">Grand Total</th>
    </tr>
  </thead>
  <tbody>
    <tr id='order-info'>
      <th scope="row"><%= @order.id %></th>
      <td><%= @order.created_at.strftime("%m/%d/%Y") %></td>
      <td><%= @order.updated_at.strftime("%m/%d/%Y") %></td>
      <td><%= @order.status.capitalize %></td>
      <td><%= @order.total_item_quantity %></td>
      <td><%= number_to_currency(@order.grandtotal) %></td>
    </tr>
  </tbody>
</table>


<h2 class="text-center mb-4 mt-5">Item Details</h2>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">Item</th>
        <th scope="col">Description</th>
        <th scope="col">Image</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Subtotal</th>
      </tr>
    </thead>
    <tbody>

      <% @order.item_orders.each do |item_order|%>
      <tr>
      <section id = "item-<%=item_order.item_id%>">
        <th><%= item_order.item.name %></th>
        <td><%= item_order.item.description %></td>
        <td align='center'><%= image_tag item_order.item.image%> </td>
        <td><%= number_to_currency(item_order.price)%></td>
        <td><%= item_order.quantity%></td>
        <td><%= number_to_currency(item_order.subtotal)%></td>
        </section>
      </tr>
      <% end %>
    </tbody>
  </table>

<% if @order.pending? || @order.packaged? %>
  <article class="justify-content-center row">
    <%= button_to 'Cancel Order', "/profile/orders/#{@order.id}", method: :patch, class: 'btn btn-danger mt-4' %>
  </article>
<% end %>

<br>

app/views/partials/_user_orders_index.html.erb
<h1 class="mt-4 mb-4"><%= name %> Orders</h1>

<table class="table table-striped table-bordered cart-table">
  <thead>
    <tr>
      <th scope="col">Order ID</th>
      <th scope="col">Date Created</th>
      <th scope="col">Date Updated</th>
      <th scope="col">Current Status</th>
      <th scope="col">Number of Items</th>
      <th scope="col">Grand Total</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr id="order-<%= order.id %>">
        <th scope="row"><%= link_to "#{order.id}", order_show_path + "#{order.id}", method: :get %></th>
        <td><%= order.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= order.updated_at.strftime("%m/%d/%Y") %></td>
        <td><%= order.status.capitalize %></td>
        <td><%= order.item_orders.count %></td>
        <td><%= number_to_currency(order.grandtotal) %></td>
          <% if order.pending? || order.packaged? %>
            <article class="justify-content-center row">
              <td><%= button_to 'Cancel Order', "/profile/orders/#{order.id}", method: :patch, class: 'btn btn-danger mt-4' %></td>
            </article>
          <% end %>
          <% if order.pending? && !current_admin? %>
            <article class="justify-content-center row">
              <td><%= button_to 'Change Address', "/profile/orders/#{order.id}/edit", method: :get, class: 'btn btn-success mt-4' %></td>
            </article>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_user_profile.html.erb
<h1 class="mt-4 text-center">Hello, <%= @user.name %></h1>

<br>

<table class="profile-info">
  <tr>
    <td>Name</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @user.email %></td>
  </tr>
</table>

<br>

<h3 class="mt-4 text-center">Addresses</h3>
<center>
  <table class="address-info">
    <tr>
      <th>Nickname</th>
      <th>Street Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
    </tr>
      <% @user.addresses.each do |address| %>
      <tr>
        <td><%= address.nickname %></td>
        <td><%= address.address %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zip %></td>
      </tr>
      <% end %>
  </table>
</center>
<article class="justify-content-center row mt-4">
  <% if !@user.orders.empty? %>
    <%= link_to 'Your Orders', user_orders_path, class: 'btn btn-success ml-2 mr-2' %>
  <% end %>
  <% if !admin %>
    <%= link_to 'Edit Your Info', '/profile/edit', class: 'btn btn-primary ml-2 mr-2' %>
    <%= link_to 'Change Your Password', '/profile/edit?info=false', class: 'btn btn-danger ml-2 mr-2' %>
    <%= link_to 'Edit Address', '/profile/addresses', class: 'btn btn-success ml-2 mr-2' %>
  <% end %>
</article>